# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.10.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.10.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/silkcut/source/SimpleServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/silkcut/source/SimpleServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.10.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.10.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/silkcut/source/SimpleServer/CMakeFiles /Users/silkcut/source/SimpleServer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/silkcut/source/SimpleServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named molten_client

# Build rule for target.
molten_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 molten_client
.PHONY : molten_client

# fast build rule for target.
molten_client/fast:
	$(MAKE) -f CMakeFiles/molten_client.dir/build.make CMakeFiles/molten_client.dir/build
.PHONY : molten_client/fast

#=============================================================================
# Target rules for targets named molten_agent

# Build rule for target.
molten_agent: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 molten_agent
.PHONY : molten_agent

# fast build rule for target.
molten_agent/fast:
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/build
.PHONY : molten_agent/fast

client.o: client.c.o

.PHONY : client.o

# target to build an object file
client.c.o:
	$(MAKE) -f CMakeFiles/molten_client.dir/build.make CMakeFiles/molten_client.dir/client.c.o
.PHONY : client.c.o

client.i: client.c.i

.PHONY : client.i

# target to preprocess a source file
client.c.i:
	$(MAKE) -f CMakeFiles/molten_client.dir/build.make CMakeFiles/molten_client.dir/client.c.i
.PHONY : client.c.i

client.s: client.c.s

.PHONY : client.s

# target to generate assembly for a file
client.c.s:
	$(MAKE) -f CMakeFiles/molten_client.dir/build.make CMakeFiles/molten_client.dir/client.c.s
.PHONY : client.c.s

common.o: common.c.o

.PHONY : common.o

# target to build an object file
common.c.o:
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/common.c.o
.PHONY : common.c.o

common.i: common.c.i

.PHONY : common.i

# target to preprocess a source file
common.c.i:
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/common.c.i
.PHONY : common.c.i

common.s: common.c.s

.PHONY : common.s

# target to generate assembly for a file
common.c.s:
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/common.c.s
.PHONY : common.c.s

event_loop.o: event_loop.c.o

.PHONY : event_loop.o

# target to build an object file
event_loop.c.o:
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/event_loop.c.o
.PHONY : event_loop.c.o

event_loop.i: event_loop.c.i

.PHONY : event_loop.i

# target to preprocess a source file
event_loop.c.i:
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/event_loop.c.i
.PHONY : event_loop.c.i

event_loop.s: event_loop.c.s

.PHONY : event_loop.s

# target to generate assembly for a file
event_loop.c.s:
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/event_loop.c.s
.PHONY : event_loop.c.s

molten_slog.o: molten_slog.c.o

.PHONY : molten_slog.o

# target to build an object file
molten_slog.c.o:
	$(MAKE) -f CMakeFiles/molten_client.dir/build.make CMakeFiles/molten_client.dir/molten_slog.c.o
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/molten_slog.c.o
.PHONY : molten_slog.c.o

molten_slog.i: molten_slog.c.i

.PHONY : molten_slog.i

# target to preprocess a source file
molten_slog.c.i:
	$(MAKE) -f CMakeFiles/molten_client.dir/build.make CMakeFiles/molten_client.dir/molten_slog.c.i
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/molten_slog.c.i
.PHONY : molten_slog.c.i

molten_slog.s: molten_slog.c.s

.PHONY : molten_slog.s

# target to generate assembly for a file
molten_slog.c.s:
	$(MAKE) -f CMakeFiles/molten_client.dir/build.make CMakeFiles/molten_client.dir/molten_slog.c.s
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/molten_slog.c.s
.PHONY : molten_slog.c.s

net_client.o: net_client.c.o

.PHONY : net_client.o

# target to build an object file
net_client.c.o:
	$(MAKE) -f CMakeFiles/molten_client.dir/build.make CMakeFiles/molten_client.dir/net_client.c.o
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/net_client.c.o
.PHONY : net_client.c.o

net_client.i: net_client.c.i

.PHONY : net_client.i

# target to preprocess a source file
net_client.c.i:
	$(MAKE) -f CMakeFiles/molten_client.dir/build.make CMakeFiles/molten_client.dir/net_client.c.i
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/net_client.c.i
.PHONY : net_client.c.i

net_client.s: net_client.c.s

.PHONY : net_client.s

# target to generate assembly for a file
net_client.c.s:
	$(MAKE) -f CMakeFiles/molten_client.dir/build.make CMakeFiles/molten_client.dir/net_client.c.s
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/net_client.c.s
.PHONY : net_client.c.s

protocol/message.o: protocol/message.c.o

.PHONY : protocol/message.o

# target to build an object file
protocol/message.c.o:
	$(MAKE) -f CMakeFiles/molten_client.dir/build.make CMakeFiles/molten_client.dir/protocol/message.c.o
.PHONY : protocol/message.c.o

protocol/message.i: protocol/message.c.i

.PHONY : protocol/message.i

# target to preprocess a source file
protocol/message.c.i:
	$(MAKE) -f CMakeFiles/molten_client.dir/build.make CMakeFiles/molten_client.dir/protocol/message.c.i
.PHONY : protocol/message.c.i

protocol/message.s: protocol/message.c.s

.PHONY : protocol/message.s

# target to generate assembly for a file
protocol/message.c.s:
	$(MAKE) -f CMakeFiles/molten_client.dir/build.make CMakeFiles/molten_client.dir/protocol/message.c.s
.PHONY : protocol/message.c.s

protocol/protocol.o: protocol/protocol.c.o

.PHONY : protocol/protocol.o

# target to build an object file
protocol/protocol.c.o:
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/protocol/protocol.c.o
.PHONY : protocol/protocol.c.o

protocol/protocol.i: protocol/protocol.c.i

.PHONY : protocol/protocol.i

# target to preprocess a source file
protocol/protocol.c.i:
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/protocol/protocol.c.i
.PHONY : protocol/protocol.c.i

protocol/protocol.s: protocol/protocol.c.s

.PHONY : protocol/protocol.s

# target to generate assembly for a file
protocol/protocol.c.s:
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/protocol/protocol.c.s
.PHONY : protocol/protocol.c.s

server.o: server.c.o

.PHONY : server.o

# target to build an object file
server.c.o:
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/server.c.o
.PHONY : server.c.o

server.i: server.c.i

.PHONY : server.i

# target to preprocess a source file
server.c.i:
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/server.c.i
.PHONY : server.c.i

server.s: server.c.s

.PHONY : server.s

# target to generate assembly for a file
server.c.s:
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/server.c.s
.PHONY : server.c.s

smalloc.o: smalloc.c.o

.PHONY : smalloc.o

# target to build an object file
smalloc.c.o:
	$(MAKE) -f CMakeFiles/molten_client.dir/build.make CMakeFiles/molten_client.dir/smalloc.c.o
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/smalloc.c.o
.PHONY : smalloc.c.o

smalloc.i: smalloc.c.i

.PHONY : smalloc.i

# target to preprocess a source file
smalloc.c.i:
	$(MAKE) -f CMakeFiles/molten_client.dir/build.make CMakeFiles/molten_client.dir/smalloc.c.i
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/smalloc.c.i
.PHONY : smalloc.c.i

smalloc.s: smalloc.c.s

.PHONY : smalloc.s

# target to generate assembly for a file
smalloc.c.s:
	$(MAKE) -f CMakeFiles/molten_client.dir/build.make CMakeFiles/molten_client.dir/smalloc.c.s
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/smalloc.c.s
.PHONY : smalloc.c.s

socket.o: socket.c.o

.PHONY : socket.o

# target to build an object file
socket.c.o:
	$(MAKE) -f CMakeFiles/molten_client.dir/build.make CMakeFiles/molten_client.dir/socket.c.o
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/socket.c.o
.PHONY : socket.c.o

socket.i: socket.c.i

.PHONY : socket.i

# target to preprocess a source file
socket.c.i:
	$(MAKE) -f CMakeFiles/molten_client.dir/build.make CMakeFiles/molten_client.dir/socket.c.i
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/socket.c.i
.PHONY : socket.c.i

socket.s: socket.c.s

.PHONY : socket.s

# target to generate assembly for a file
socket.c.s:
	$(MAKE) -f CMakeFiles/molten_client.dir/build.make CMakeFiles/molten_client.dir/socket.c.s
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/socket.c.s
.PHONY : socket.c.s

sstring.o: sstring.c.o

.PHONY : sstring.o

# target to build an object file
sstring.c.o:
	$(MAKE) -f CMakeFiles/molten_client.dir/build.make CMakeFiles/molten_client.dir/sstring.c.o
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/sstring.c.o
.PHONY : sstring.c.o

sstring.i: sstring.c.i

.PHONY : sstring.i

# target to preprocess a source file
sstring.c.i:
	$(MAKE) -f CMakeFiles/molten_client.dir/build.make CMakeFiles/molten_client.dir/sstring.c.i
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/sstring.c.i
.PHONY : sstring.c.i

sstring.s: sstring.c.s

.PHONY : sstring.s

# target to generate assembly for a file
sstring.c.s:
	$(MAKE) -f CMakeFiles/molten_client.dir/build.make CMakeFiles/molten_client.dir/sstring.c.s
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/sstring.c.s
.PHONY : sstring.c.s

timer.o: timer.c.o

.PHONY : timer.o

# target to build an object file
timer.c.o:
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/timer.c.o
.PHONY : timer.c.o

timer.i: timer.c.i

.PHONY : timer.i

# target to preprocess a source file
timer.c.i:
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/timer.c.i
.PHONY : timer.c.i

timer.s: timer.c.s

.PHONY : timer.s

# target to generate assembly for a file
timer.c.s:
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/timer.c.s
.PHONY : timer.c.s

worker_pool.o: worker_pool.c.o

.PHONY : worker_pool.o

# target to build an object file
worker_pool.c.o:
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/worker_pool.c.o
.PHONY : worker_pool.c.o

worker_pool.i: worker_pool.c.i

.PHONY : worker_pool.i

# target to preprocess a source file
worker_pool.c.i:
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/worker_pool.c.i
.PHONY : worker_pool.c.i

worker_pool.s: worker_pool.c.s

.PHONY : worker_pool.s

# target to generate assembly for a file
worker_pool.c.s:
	$(MAKE) -f CMakeFiles/molten_agent.dir/build.make CMakeFiles/molten_agent.dir/worker_pool.c.s
.PHONY : worker_pool.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... molten_client"
	@echo "... molten_agent"
	@echo "... client.o"
	@echo "... client.i"
	@echo "... client.s"
	@echo "... common.o"
	@echo "... common.i"
	@echo "... common.s"
	@echo "... event_loop.o"
	@echo "... event_loop.i"
	@echo "... event_loop.s"
	@echo "... molten_slog.o"
	@echo "... molten_slog.i"
	@echo "... molten_slog.s"
	@echo "... net_client.o"
	@echo "... net_client.i"
	@echo "... net_client.s"
	@echo "... protocol/message.o"
	@echo "... protocol/message.i"
	@echo "... protocol/message.s"
	@echo "... protocol/protocol.o"
	@echo "... protocol/protocol.i"
	@echo "... protocol/protocol.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
	@echo "... smalloc.o"
	@echo "... smalloc.i"
	@echo "... smalloc.s"
	@echo "... socket.o"
	@echo "... socket.i"
	@echo "... socket.s"
	@echo "... sstring.o"
	@echo "... sstring.i"
	@echo "... sstring.s"
	@echo "... timer.o"
	@echo "... timer.i"
	@echo "... timer.s"
	@echo "... worker_pool.o"
	@echo "... worker_pool.i"
	@echo "... worker_pool.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

